# Generated by Django 3.1 on 2020-09-07 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200907_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 7, 23, 4, 34, 317705)),
        ),
    ]
