# Generated by Django 3.1 on 2020-09-08 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20200908_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 8, 10, 41, 23, 463653, tzinfo=utc)),
        ),
    ]
