# Generated by Django 3.1 on 2020-09-11 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20200909_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
