# Generated by Django 3.1 on 2020-09-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20200911_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='upload/%Y/%m/%d/'),
        ),
    ]
