# Generated by Django 3.1 on 2020-09-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listing_photo_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bedrooms_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='bethrooms_size',
            field=models.IntegerField(default=0),
        ),
    ]
