# Generated by Django 3.1 on 2020-09-09 02:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0007_auto_20200909_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 9, 2, 30, 42, 217711, tzinfo=utc)),
        ),
    ]
